FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    python3 \
    python3-pip \
    wget \
    libopenblas-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN git clone https://github.com/ggerganov/llama.cpp.git &&\
    cd llama.cpp &&\
    cmake -B build &&\
    cmake --build build --config Release -j 8

RUN mkdir -p /app/models

RUN pip3 install fastapi uvicorn python-multipart gunicorn

COPY llama_cpp_api.py /app/

ENV LLAMA_CPP_PATH=/app/llama.cpp/build/bin/llama-qwen2vl-cli
ENV QWEN2VL_MODEL_PATH=/app/models/Qwen2-VL-2B-Instruct-Q4_K_M.gguf
ENV MM_PROJ_PATH=/app/models/mmproj-Qwen2-VL-2B-Instruct-f16.gguf

EXPOSE 8080

# CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "-b", "0.0.0.0:8080", "--workers", "4", "llama_cpp_api:app"]
CMD ["python3", "llama_cpp_api.py"]

# Build
# docker build -t llama_cpp_service -f Dockerfile.llama_cpp .

# Run
# docker run \
#   --name llama_cpp_service \
#   -v $(pwd)/models:/app/models \
#   --network chatbot_network \
#   -p 8080:8080 \
#   llama_cpp_service