FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt /app/

RUN pip3 install -r requirements.txt

COPY . /app

EXPOSE 8000

CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "-b", "0.0.0.0:8000", "--workers", "4", "api:app"]


# docker build -t chatbot_backend -f Dockerfile.fastapi .

# docker run \
#   --name chatbot_backend \
#   -v $(pwd):/app \
#   --network chatbot_network \
#   -p 8000:8000 \
#   -e OLLAMA_API_URL=http://ollama_service:11434/api/generate \
#   -e LLAMACPP_API_URL=http://llama_cpp_service:8080/generate-vision \
#   chatbot_backend