[project]
name = "deployemt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.8",
    "gradio>=5.16.2",
    "pydantic>=2.10.6",
    "requests>=2.32.3",
]
